In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[5,12,7]], columns=["cgpa","profile_score","lpa"])

In [3]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model=Sequential()
model.add(Dense(2,activation="sigmoid", input_dim=2))
model.add(Dense(1,activation='sigmoid'))

e:\Conda\envs\Machine_Learning\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[-0.76542324,  0.47848284],
        [-1.1762539 ,  0.04662013]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-0.13136566],
        [ 0.13762534]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights=[np.array([[0.1, 0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [8]:
model.set_weights(new_weights)

In [9]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss="binary_crossentropy",optimizer=optimizer)

In [11]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: -0.1306
Epoch 2/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: -0.1722
Epoch 3/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: -0.2155
Epoch 4/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - loss: -0.2624
Epoch 5/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: -0.3036
Epoch 6/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: -0.3517
Epoch 7/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: -0.3909
Epoch 8/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - loss: -0.4357
Epoch 9/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - loss: -0.4803
Epoch 10/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - loss: -0.5304 
Epoch 11/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step - loss: -0.5732
Epoch 12/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: -0.6126 
Epoch 13/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - loss: -0.6578 
Epoch 14/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: -0.7045
Epoch 15/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: -0.7481
Epoch 16/75
3/3 