In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.DataFrame([[8,8,4],[7,9,5],[5,12,7]], columns=["cgpa","profile_score","lpa"])

In [3]:
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [4]:
model = Sequential()
model.add(Dense(2,activation="linear", input_dim=2))
model.add(Dense(1,activation="linear"))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [6]:
model.get_weights()

[array([[ 0.75735784, -0.9419787 ],
        [ 0.71532214, -0.29113555]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.13452125],
        [0.83139884]], dtype=float32),
 array([0.], dtype=float32)]

In [7]:
new_weights=[np.array([[0.1, 0.1],[0.1,0.1]],dtype=np.float32),
             np.array([0.,0.],dtype=np.float32),
             np.array([[0.1],[0.1]],dtype=np.float32),
             np.array([0.],dtype=np.float32)]

In [8]:
model.set_weights(new_weights)

In [9]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [10]:
optimizer=keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error',optimizer=optimizer)

In [11]:
model.fit(df.iloc[:,0:-1].values,df['lpa'].values,epochs=75,verbose=1,batch_size=1)

Epoch 1/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 21ms/step - loss: 26.5271
Epoch 2/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 26.2770
Epoch 3/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - loss: 26.0556 
Epoch 4/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - loss: 25.8091
Epoch 5/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - loss: 25.5719
Epoch 6/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 25.3433
Epoch 7/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 25.0632
Epoch 8/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step - loss: 24.8206
Epoch 9/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - loss: 24.5587
Epoch 10/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step - loss: 24.2851 
Epoch 11/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - loss: 24.0066
Epoch 12/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step - loss: 23.6985 
Epoch 13/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 34ms/step - loss: 23.4046
Epoch 14/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 23.1076
Epoch 15/75
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step - loss: 22.8372
Epoch 16/75
3/3 

In [12]:
model.get_weights()

[array([[0.33175763, 0.33175763],
        [0.3159181 , 0.3159181 ]], dtype=float32),
 array([0.22636263, 0.22636263], dtype=float32),
 array([[0.3260963],
        [0.3260963]], dtype=float32),
 array([0.17737222], dtype=float32)]